name: CI / gate

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-tests:
    uses: ./.github/workflows/run-tests.yml

  qodana:
    uses: ./.github/workflows/qodana_code_quality.yml
    secrets:
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_689838719 }}
    with:
      sha: ${{ github.event.pull_request.head.sha }}

  android-instrumentation-tests:
    uses: ./.github/workflows/android-instrumentation-tests.yml

  gate:
    name: Required Checks Validation
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [unit-tests, qodana, android-instrumentation-tests]
    steps:
      - run: echo "All required checks passed"
